// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC01vyHrnjEyEucvqjq1ovxd0JJSC3zonE',
    appId: '1:907139628831:web:9844611a48ab22ca4f3a2a',
    messagingSenderId: '907139628831',
    projectId: 'mini--project-1',
    authDomain: 'mini--project-1.firebaseapp.com',
    storageBucket: 'mini--project-1.appspot.com',
    measurementId: 'G-75KL08XNST',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB31vze32HPkL_v7_bVAa82VDlJR9sGcsI',
    appId: '1:907139628831:android:88f8085755e4eecf4f3a2a',
    messagingSenderId: '907139628831',
    projectId: 'mini--project-1',
    storageBucket: 'mini--project-1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAJg4o_ElgEByZn3HUykvM_90GmOm5TKGc',
    appId: '1:907139628831:ios:caf7f72bce5763ba4f3a2a',
    messagingSenderId: '907139628831',
    projectId: 'mini--project-1',
    storageBucket: 'mini--project-1.appspot.com',
    iosClientId: '907139628831-0ivt4n6b30ccbqrg3gupb1dn3643749i.apps.googleusercontent.com',
    iosBundleId: 'com.example.whatsappUi',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAJg4o_ElgEByZn3HUykvM_90GmOm5TKGc',
    appId: '1:907139628831:ios:caf7f72bce5763ba4f3a2a',
    messagingSenderId: '907139628831',
    projectId: 'mini--project-1',
    storageBucket: 'mini--project-1.appspot.com',
    iosClientId: '907139628831-0ivt4n6b30ccbqrg3gupb1dn3643749i.apps.googleusercontent.com',
    iosBundleId: 'com.example.whatsappUi',
  );
}
